using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Zwedze.Aetherweave.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AllKnownMembersGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MissingPartialRule = new(
        "ZFCG001",
        "Type must be partial",
        "'{0}' must be declared partial to generate the AllKnown property",
        "SourceGeneration",
        DiagnosticSeverity.Warning,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject opt-in attribute into the user compilation
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(
                "GenerateAllKnownMembersAttribute.g.cs",
                """

                // <auto-generated/>
                namespace Zwedze.Framework.Common
                {
                    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                    internal sealed class GenerateAllKnownMembersAttribute : System.Attribute
                    {
                        public string PropertyName { get; }
                        public GenerateAllKnownMembersAttribute(string propertyName = null)
                        {
                            PropertyName = propertyName;
                        }
                    }
                }

                """);
        });

        var targets = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0,
                static (ctx, _) =>
                {
                    var cls = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls);
                    if (symbol == null)
                    {
                        return default;
                    }

                    foreach (var attr in symbol.GetAttributes())
                    {
                        var name = attr.AttributeClass?.ToDisplayString();
                        if (name == "Zwedze.Framework.Common.GenerateAllKnownMembersAttribute")
                        {
                            string? propertyName = null;
                            if (attr.ConstructorArguments.Length == 1 && !attr.ConstructorArguments[0].IsNull)
                            {
                                propertyName = attr.ConstructorArguments[0].Value as string;
                            }

                            return new Target(symbol, propertyName);
                        }
                    }

                    return default;
                })
            // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
            .Where(static t => t.Symbol is not null);

        context.RegisterSourceOutput(
            targets.Collect(),
            static (spc, collected) =>
            {
                var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in collected)
                {
                    // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
                    if (t.Symbol is null)
                    {
                        continue; // <— guard
                    }

                    if (!seen.Add(t.Symbol))
                    {
                        continue;
                    }

                    EmitFor(spc, t);
                }
            });
    }

    private static void EmitFor(SourceProductionContext spc, Target target)
    {
        var type = target.Symbol;
        var typeName = type.Name;
        var ns = type.ContainingNamespace != null && !type.ContainingNamespace.IsGlobalNamespace ? type.ContainingNamespace.ToDisplayString() : null;

        var access = AccessibilityKeyword(type.DeclaredAccessibility);

        // Require the user type to be partial
        if (!type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax cds && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))))
        {
            var diagnostic = Diagnostic.Create(
                MissingPartialRule,
                type.Locations.FirstOrDefault(),
                typeName);
            spc.ReportDiagnostic(diagnostic);
            return;
        }

        // Gather static fields/properties of the same type
        var members = type
            .GetMembers()
            .Where(m =>
            {
                if (m is IFieldSymbol { IsStatic: true } f && SymbolEqualityComparer.Default.Equals(f.Type, type))
                {
                    return true;
                }

                var p = m as IPropertySymbol;
                return p is { IsStatic: true, GetMethod: not null }
                       && SymbolEqualityComparer.Default.Equals(p.Type, type);
            })
            .OrderBy(m => m.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
            .Select(m => m.Name)
            .Distinct(StringComparer.Ordinal)
            .ToImmutableArray();

        if (members.Length == 0)
        {
            return;
        }

        var propertyName = !string.IsNullOrWhiteSpace(target.PropertyName)
            ? target.PropertyName
            : "AllKnown" + typeName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        if (ns != null)
        {
            sb.AppendLine("namespace " + ns + ";\n");
        }

        sb.AppendLine(access + "partial class " + typeName);
        sb.AppendLine("{");
        sb.AppendLine("    " + access + "static " + typeName + "[] " + propertyName + " => new " + typeName + "[]");
        sb.AppendLine("    {");
        for (var i = 0; i < members.Length; i++)
        {
            var suffix = i < members.Length - 1 ? "," : string.Empty;
            sb.AppendLine("        " + members[i] + suffix);
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        spc.AddSource(
            typeName + ".AllKnown.g.cs",
            sb.ToString());
    }

    private static string AccessibilityKeyword(Accessibility a)
    {
        switch (a)
        {
            case Accessibility.Public:
                return "public ";
            case Accessibility.Internal:
                return "internal ";
            case Accessibility.Protected:
                return "protected ";
            case Accessibility.Private:
                return "private ";
            case Accessibility.ProtectedOrInternal:
                return "protected internal ";
            case Accessibility.ProtectedAndInternal:
                return "private protected ";
            default:
                return string.Empty; // NotApplicable, etc.
        }
    }

    private struct Target(INamedTypeSymbol symbol, string? propertyName)
    {
        public readonly INamedTypeSymbol Symbol = symbol;
        public readonly string? PropertyName = propertyName;
    }
}
