using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Zwedze.Aetherweave.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CodeMapperGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MissingPartialRule = new(
        "ZFCG002",
        "Type must be partial",
        "'{0}' must be declared partial to generate the code mapper",
        "SourceGeneration",
        DiagnosticSeverity.Warning,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the opt-in attribute
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(
                "GenerateCodeMapperAttribute.g.cs",
                @"
// <auto-generated/>
namespace Zwedze.Framework.Common;

[System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GenerateCodeMapperAttribute : System.Attribute
{
    // Name of the property on each instance that stores its code (default: ""Code"")
    public string CodePropertyName { get; }
    // Name of the generated method (default: ""FromCode"")
    public string MethodName { get; }
    public GenerateCodeMapperAttribute(string codePropertyName = ""Code"", string methodName = ""FromCode"")
    {
        CodePropertyName = codePropertyName;
        MethodName = methodName;
    }
}
");
        });

        // Find classes with [GenerateCodeMapper]
        var targets = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                static (ctx, _) =>
                {
                    var cls = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls);
                    if (symbol == null)
                    {
                        return default;
                    }

                    foreach (var a in symbol.GetAttributes())
                    {
                        if (a.AttributeClass?.ToDisplayString() == "Zwedze.Framework.Common.GenerateCodeMapperAttribute")
                        {
                            var codeProp = "Code";
                            var method = "FromCode";

                            if (a.ConstructorArguments.Length >= 1 && !a.ConstructorArguments[0].IsNull)
                            {
                                codeProp = a.ConstructorArguments[0].Value as string ?? codeProp;
                            }
                            if (a.ConstructorArguments.Length >= 2 && !a.ConstructorArguments[1].IsNull)
                            {
                                method = a.ConstructorArguments[1].Value as string ?? method;
                            }

                            foreach (var kv in a.NamedArguments)
                            {
                                if (kv.Key == "CodePropertyName" && !kv.Value.IsNull)
                                {
                                    codeProp = kv.Value.Value as string ?? codeProp;
                                }
                                if (kv.Key == "MethodName" && !kv.Value.IsNull)
                                {
                                    method = kv.Value.Value as string ?? method;
                                }
                            }

                            return new Target(symbol, codeProp, method);
                        }
                    }

                    return default;
                })
            // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
            .Where(static t => t.Symbol != null);

        // Emit once per distinct type
        context.RegisterSourceOutput(
            targets.Collect(),
            static (spc, collected) =>
            {
                var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in collected)
                {
                    // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
                    if (t.Symbol == null)
                    {
                        continue;
                    }

                    if (!seen.Add(t.Symbol))
                    {
                        continue;
                    }

                    EmitMapper(spc, t);
                }
            });
    }

    private static void EmitMapper(SourceProductionContext spc, Target t)
    {
        var type = t.Symbol;
        var ns = type.ContainingNamespace != null && !type.ContainingNamespace.IsGlobalNamespace ? type.ContainingNamespace.ToDisplayString() : null;

        // Require partial (same policy as your other generator)
        if (!type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax cds && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))))
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                MissingPartialRule,
                type.Locations.FirstOrDefault(),
                type.Name));
            return;
        }

        // Collect static fields/properties of the same type
        var members = type
            .GetMembers()
            .Where(m =>
            {
                var f = m as IFieldSymbol;
                if (f?.IsStatic == true && SymbolEqualityComparer.Default.Equals(f.Type, type))
                {
                    return true;
                }
                var p = m as IPropertySymbol;
                return p is { IsStatic: true, GetMethod: not null } && SymbolEqualityComparer.Default.Equals(p.Type, type);
            })
            .OrderBy(m => m.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
            .Select(m => m.Name)
            .ToArray();

        if (members.Length == 0)
        {
            return;
        }

        var access = AccessibilityKeyword(type.DeclaredAccessibility);
        var typeName = type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var methodName = t.MethodName;
        var codeProp = t.CodePropertyName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        if (ns != null)
        {
            sb.AppendLine("namespace " + ns + ";\n");
        }

        sb.AppendLine(access + "partial class " + type.Name);
        sb.AppendLine("{");
        sb.AppendLine($"    {access}static {typeName} {methodName}(Zwedze.Aetherweave.SharedKernel.Code<{typeName}> code)");
        sb.AppendLine("    {");
        foreach (var m in members)
        {
            sb.AppendLine($"        if (object.Equals(code, {m}.{codeProp})) return {m};");
        }
        sb.AppendLine($"        throw new System.ArgumentException(\"Unknown {type.Name} code: \" + code);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    {access}static {typeName} {methodName}(string code) => {methodName}((Zwedze.Aetherweave.SharedKernel.Code<{typeName}>)code);");
        sb.AppendLine("}");

        spc.AddSource(type.Name + ".CodeMapper.g.cs", sb.ToString());
    }

    private static string AccessibilityKeyword(Accessibility a)
    {
        switch (a)
        {
            case Accessibility.Public:
                return "public ";
            case Accessibility.Internal:
                return "internal ";
            case Accessibility.Protected:
                return "protected ";
            case Accessibility.Private:
                return "private ";
            case Accessibility.ProtectedOrInternal:
                return "protected internal ";
            case Accessibility.ProtectedAndInternal:
                return "private protected ";
            default:
                return string.Empty;
        }
    }

    private struct Target(
        INamedTypeSymbol symbol,
        string codePropertyName,
        string methodName)
    {
        public readonly INamedTypeSymbol Symbol = symbol;
        public readonly string CodePropertyName = codePropertyName;
        public readonly string MethodName = methodName;
    }
}
