using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Zwedze.Aetherweave.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class SmartEnumGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MissingPartialRule = new(
        "ZFCG003",
        "Type must be partial",
        "'{0}' must be declared partial to generate the smart enum methods",
        "SourceGeneration",
        DiagnosticSeverity.Warning,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the opt-in attribute
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(
                "SmartEnumAttribute.g.cs",
                @"
// <auto-generated/>
namespace Zwedze.Aetherweave;

[System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class SmartEnumAttribute() : System.Attribute;
");
        });

        // Find classes with [SmartEnum]
        var targets = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) =>
                {
                    var cls = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls);
                    return symbol is null ? default : FindTarget(symbol);
                })
            // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
            .Where(static t => t.Symbol != null);

        // Emit once per distinct type
        context.RegisterSourceOutput(
            targets.Collect(),
            static (spc, collected) =>
            {
                var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var t in collected)
                {
                    if (!seen.Add(t.Symbol))
                    {
                        continue;
                    }

                    EmitMapper(spc, t);
                }
            });
        return;

        static Target FindTarget(INamedTypeSymbol symbol)
        {
            var isAttributeFound = symbol
                .GetAttributes()
                .Any(a => a.AttributeClass?.ToDisplayString() == "Zwedze.Aetherweave.SmartEnumAttribute");
            return isAttributeFound ? new Target(symbol) : default;
        }
    }

    private static void EmitMapper(SourceProductionContext spc, Target t)
    {
        var type = t.Symbol;
        var ns = type.ContainingNamespace is { IsGlobalNamespace: false } ? type.ContainingNamespace.ToDisplayString() : null;

        if (!DoesPartialClassExists(type))
        {
            var diagnostic = Diagnostic.Create(
                MissingPartialRule,
                type.Locations.FirstOrDefault(),
                type.Name);
            spc.ReportDiagnostic(diagnostic);
            return;
        }

        // Collect static fields/properties of the same type as the decorated type
        var members = type
            .GetMembers()
            .Where(m =>
            {
                var f = m as IFieldSymbol;
                if (f?.IsStatic == true && SymbolEqualityComparer.Default.Equals(f.Type, type))
                {
                    return true;
                }
                var p = m as IPropertySymbol;
                return p is { IsStatic: true, GetMethod: not null } && SymbolEqualityComparer.Default.Equals(p.Type, type);
            })
            .OrderBy(m => m.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
            .Select(m => m.Name)
            .ToArray();

        if (members.Length == 0)
        {
            return;
        }

        var access = AccessibilityKeyword(type.DeclaredAccessibility);
        var typeName = type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        if (ns != null)
        {
            sb.AppendLine("namespace " + ns + ";\n");
        }

        sb.AppendLine(access + "partial class " + type.Name);
        sb.AppendLine("{");
        AppendConstructor();
        sb.AppendLine();
        AppendProperties();
        sb.AppendLine();
        AppendFromCodeMethods();
        sb.AppendLine();
        AppendAllValuesProperty();
        sb.AppendLine("}");

        spc.AddSource(type.Name + ".SmartEnum.g.cs", sb.ToString());

        void AppendConstructor()
        {
            sb.AppendLine($"    private {typeName}(string code)");
            sb.AppendLine("    {");
            sb.AppendLine($"        Code = Zwedze.Aetherweave.SharedKernel.Code<{typeName}>.From(code);");
            sb.AppendLine("    }");
        }

        void AppendProperties()
        {
            sb.AppendLine($"    public Zwedze.Aetherweave.SharedKernel.Code<{typeName}> Code {{ get; }}");
        }

        void AppendFromCodeMethods()
        {
            sb.AppendLine($"    {access}static {typeName} FromCode(Zwedze.Aetherweave.SharedKernel.Code<{typeName}> code)");
            sb.AppendLine("    {");
            foreach (var m in members)
            {
                sb.AppendLine($"        if (object.Equals(code, {m}.Code)) return {m};");
            }
            sb.AppendLine($"        throw new System.ArgumentException(\"Unknown {type.Name} code: \" + code);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    {access}static {typeName} FromCode(string code) => FromCode(Zwedze.Aetherweave.SharedKernel.Code<{typeName}>.From(code));");
        }

        void AppendAllValuesProperty()
        {
            sb.AppendLine("    " + access + "static " + typeName + "[] AllValues => new " + typeName + "[]");
            sb.AppendLine("    {");
            for (var i = 0; i < members.Length; i++)
            {
                var suffix = i < members.Length - 1 ? "," : string.Empty;
                sb.AppendLine("        " + members[i] + suffix);
            }
            sb.AppendLine("    };");
        }
    }

    private static bool DoesPartialClassExists(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is ClassDeclarationSyntax cds && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));
    }

    private static string AccessibilityKeyword(Accessibility a)
    {
        switch (a)
        {
            case Accessibility.Public:
                return "public ";

            case Accessibility.Internal:
                return "internal ";

            case Accessibility.Protected:
                return "protected ";

            case Accessibility.Private:
                return "private ";

            case Accessibility.ProtectedOrInternal:
                return "protected internal ";

            case Accessibility.ProtectedAndInternal:
                return "private protected ";

            default:
                return string.Empty;
        }
    }

    private struct Target(INamedTypeSymbol symbol)
    {
        public readonly INamedTypeSymbol Symbol = symbol;
    }
}
