namespace Zwedze.Aetherweave.SharedKernel.DomainEvents;

/// <summary>
///     Dispatcher for domain events
///     Implementation is generated by source generator
/// </summary>
public interface IDomainEventDispatcher
{
    Task DispatchAsync(IHasDomainEvents aggregate, CancellationToken cancellationToken = default);
    Task DispatchAsync(IDomainEvent domainEvent, CancellationToken cancellationToken = default);
}
